baseURL = 'https://quentb.com'
languageCode = 'en-us'
title = 'Quentin Baker'
theme = 'archie'
copyright = '© Quentin Baker'
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode = 'toggle' # color-mode → light,dark,toggle or auto
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = '*Typing Noises*'
	
[[params.social]]
name = 'GitHub'
icon = 'github'
url = 'https://github.com/qrbaker'

[[params.social]]
name = 'LinkedIn'
icon = 'linkedin'
url = 'https://www.linkedin.com/in/quentin-baker/'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
